server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///c:/Users/safiy/OneDrive/Bureau/video-streaming-microservices/config-repo
          default-label: main
