services:
  video-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: video_db
    ports:
      - "3307:3306"

  user-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
    ports:
      - "3308:3306"

  discovery-service:
    build: ./backend/discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-service:
    build: ./backend/config-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    volumes:
      - ./backend/config-repo:/config-repo

  gateway-service:
    build: ./backend/gateway-service
    ports:
      - "8222:8222"
    depends_on:
      - config-service
      - discovery-service

  videoservice:
    build: ./backend/videoservice
    ports:
      - "8081:8081"
    depends_on:
      video-db:
        condition: service_started
      config-service:
        condition: service_started
      discovery-service:
        condition: service_started

  user-service:
    build: ./backend/user-service
    ports:
      - "8082:8082"
    depends_on:
      user-db:
        condition: service_started
      config-service:
        condition: service_started
      discovery-service:
        condition: service_started
